// Generated by gencpp from file learn_comm/AddTwoInts.msg
// DO NOT EDIT!


#ifndef LEARN_COMM_MESSAGE_ADDTWOINTS_H
#define LEARN_COMM_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <learn_comm/AddTwoIntsRequest.h>
#include <learn_comm/AddTwoIntsResponse.h>


namespace learn_comm
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace learn_comm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::learn_comm::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::learn_comm::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::learn_comm::AddTwoInts > {
  static const char* value()
  {
    return "learn_comm/AddTwoInts";
  }

  static const char* value(const ::learn_comm::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::learn_comm::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::learn_comm::AddTwoInts >
template<>
struct MD5Sum< ::learn_comm::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::learn_comm::AddTwoInts >::value();
  }
  static const char* value(const ::learn_comm::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::learn_comm::AddTwoIntsRequest> should match
// service_traits::DataType< ::learn_comm::AddTwoInts >
template<>
struct DataType< ::learn_comm::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::learn_comm::AddTwoInts >::value();
  }
  static const char* value(const ::learn_comm::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::learn_comm::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::learn_comm::AddTwoInts >
template<>
struct MD5Sum< ::learn_comm::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::learn_comm::AddTwoInts >::value();
  }
  static const char* value(const ::learn_comm::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::learn_comm::AddTwoIntsResponse> should match
// service_traits::DataType< ::learn_comm::AddTwoInts >
template<>
struct DataType< ::learn_comm::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::learn_comm::AddTwoInts >::value();
  }
  static const char* value(const ::learn_comm::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEARN_COMM_MESSAGE_ADDTWOINTS_H
